# Generated by Django 5.1 on 2024-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_categories_produit_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('numero', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_commande', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
