# Generated by Django 5.1 on 2024-08-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='categories',
            new_name='categorie',
        ),
    ]
