# Generated by Django 5.1 on 2024-09-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_commande_options_commande_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_ajout']},
        ),
    ]
